# Generated by Django 5.1.6 on 2025-03-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='forum_attachments/%Y/%m/%d/', verbose_name='Archivo')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('mimetype', models.CharField(max_length=50, verbose_name='Tipo MIME')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum_conversation.topic', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
                ('topics', models.ManyToManyField(related_name='tags', to='forum_conversation.topic', verbose_name='Temas')),
            ],
            options={
                'verbose_name': 'Etiqueta de tema',
                'verbose_name_plural': 'Etiquetas de temas',
                'ordering': ['name'],
            },
        ),
    ]
