# Generated by Django 5.1.6 on 2025-03-01 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_machina', '0001_initial'),
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicattachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_attachments', to='forum_conversation.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='topicattachment',
            name='file',
            field=models.FileField(upload_to='forum_attachments', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='topicattachment',
            name='mimetype',
            field=models.CharField(max_length=100, verbose_name='Tipo MIME'),
        ),
    ]
