# Generated by Django 5.1.6 on 2025-04-30 06:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_categoriaproducto_remove_product_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_min', models.DecimalField(decimal_places=2, help_text='Distancia mínima en kilómetros', max_digits=5)),
                ('distancia_max', models.DecimalField(decimal_places=2, help_text='Distancia máxima en kilómetros', max_digits=5)),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo del envío', max_digits=10)),
            ],
            options={
                'verbose_name': 'Tarifa de Envío',
                'verbose_name_plural': 'Tarifas de Envío',
                'ordering': ['distancia_min'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='listadeseos',
            name='producto',
            field=models.ForeignKey(db_column='producto_id_id', on_delete=django.db.models.deletion.CASCADE, to='marketplace.producto'),
        ),
        migrations.AlterModelTable(
            name='listadeseos',
            table='marketplace_lista_deseos',
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/imagenes/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='marketplace.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ValoracionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('titulo', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('utilidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración de Producto',
                'verbose_name_plural': 'Valoraciones de Productos',
                'ordering': ['-fecha_valoracion'],
                'unique_together': {('producto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='marketplace.valoracionproducto')),
            ],
            options={
                'verbose_name': 'Respuesta a Valoración',
                'verbose_name_plural': 'Respuestas a Valoraciones',
            },
        ),
    ]
