# Generated by Django 5.1.6 on 2025-05-01 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_direccionenvio_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificacionMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_AGOTADO', 'Stock Agotado'), ('STOCK_BAJO', 'Stock Bajo'), ('NUEVA_VENTA', 'Nueva Venta'), ('PEDIDO_COMPLETADO', 'Pedido Completado'), ('NUEVA_VALORACION', 'Nueva Valoración'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito')], default='INFO', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='marketplace.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_marketplace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Marketplace',
                'verbose_name_plural': 'Notificaciones de Marketplace',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
