# Generated by Django 5.1.6 on 2025-05-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_compra_estado_notificacionmarketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_inventario_id',
            field=models.IntegerField(blank=True, help_text='ID del producto en el inventario original', null=True),
        ),
    ]
