# Generated by Django 4.2.9 on 2024-10-10 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('categoria_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria_padre_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('comprador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('direccion_envio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('estado_compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('estado_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceProducto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('categoria_producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.categoriaproducto')),
                ('estado_producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.estadoproducto')),
                ('ubicacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('unidad_medida_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionProducto',
            fields=[
                ('valoracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproducto')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaValoracion',
            fields=[
                ('respuesta_valoracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('usuario_respuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('valoracion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.valoracionproducto')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_promocion', models.TextField()),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproducto')),
            ],
        ),
        migrations.AddField(
            model_name='marketplaceproducto',
            name='unidad_medida_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.unidadmedida'),
        ),
        migrations.AddField(
            model_name='marketplaceproducto',
            name='vendedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialPrecioProducto',
            fields=[
                ('historial_precio_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo_cambio', models.TextField(blank=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('detalle_compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.compra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceproducto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='estado_compra_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.estadocompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.metodopago'),
        ),
    ]
