# Generated by Django 5.1.6 on 2025-04-29 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_km', models.DecimalField(decimal_places=2, help_text='Radio de cobertura en kilómetros', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_servicio', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_servicio', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'Área de Servicio',
                'verbose_name_plural': 'Áreas de Servicio',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_busqueda_km', models.DecimalField(decimal_places=2, default=10.0, help_text='Radio de búsqueda preferido en kilómetros', max_digits=5)),
                ('ubicacion_preferida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencias_usuarios', to='ubicaciones.ubicacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_ubicacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Ubicación',
                'verbose_name_plural': 'Preferencias de Ubicación',
            },
        ),
        migrations.CreateModel(
            name='UbicacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='marketplace.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicación de Producto',
                'verbose_name_plural': 'Ubicaciones de Productos',
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
    ]
