# Generated by Django 4.2.9 on 2024-10-10 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTicket',
            fields=[
                ('categoria_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('estado_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('descripcion_estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaProblema',
            fields=[
                ('etiqueta_problema_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etiqueta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadTicket',
            fields=[
                ('prioridad_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prioridad', models.CharField(max_length=50)),
                ('tiempo_respuesta_estimado', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('sla_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sla', models.CharField(max_length=100)),
                ('descripcion_sla', models.TextField()),
                ('tiempo_resolucion_maximo', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_problema', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('categoria_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.categoriaticket')),
                ('estado_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.estadoticket')),
                ('prioridad_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.prioridadticket')),
                ('tecnico_asignado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketEtiqueta',
            fields=[
                ('ticket_etiqueta_id', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta_problema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.etiquetaproblema')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.ticketsoporte')),
            ],
        ),
        migrations.CreateModel(
            name='SLATicket',
            fields=[
                ('sla_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_sla', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_sla', models.DateTimeField(blank=True, null=True)),
                ('estado_sla', models.CharField(max_length=50)),
                ('sla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.sla')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.ticketsoporte')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('historial_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('accion_realizada', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('estado_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.estadoticket')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.ticketsoporte')),
                ('usuario_responsable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscalamientoTicket',
            fields=[
                ('escalamiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_escalamiento', models.IntegerField()),
                ('motivo_escalamiento', models.TextField()),
                ('fecha_escalamiento', models.DateTimeField(auto_now_add=True)),
                ('tecnico_escalado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_escalados', to=settings.AUTH_USER_MODEL)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.ticketsoporte')),
            ],
        ),
    ]
