# Generated by Django 5.1.6 on 2025-03-08 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarioalmacen',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='reservainventario',
            old_name='cantidad_reservada',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reservainventario',
            name='carrito_id',
        ),
        migrations.AddField(
            model_name='inventarioalmacen',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservainventario',
            name='usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservainventario',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
