# Generated by Django 5.1.6 on 2025-03-12 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventarioalmacen_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='user',
        ),
        migrations.AddField(
            model_name='productoinventario',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
