# Generated by Django 5.1.6 on 2025-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_almacen_propietario_proveedor_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('PARCIAL', 'Recibido Parcialmente'), ('RECIBIDO', 'Recibido Completamente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
    ]
