# Generated by Django 5.1.6 on 2025-03-13 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_pedidoproveedor_estado_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('PEDIDO_CREADO', 'Pedido Creado'), ('PEDIDO_RECIBIDO', 'Pedido Recibido'), ('PEDIDO_CANCELADO', 'Pedido Cancelado'), ('CADUCIDAD_PROXIMA', 'Caducidad Próxima'), ('MOVIMIENTO', 'Movimiento de Inventario'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito')], default='INFO', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
