# Generated by Django 5.1.6 on 2025-04-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_add_initial_categories'),
        ('inventario', '0011_notificacion'),
    ]

    operations = [
    ]
