# Generated by Django 5.1.6 on 2025-04-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_add_agro_categories'),
        ('inventario', '0012_merge_0002_add_initial_categories_0011_notificacion'),
    ]

    operations = [
    ]
