# Generated by Django 5.1.6 on 2025-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_fix_duplicate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('PEDIDO', 'Pedido a Proveedor'), ('AJUSTE', 'Ajuste de Inventario'), ('TRASPASO', 'Traspaso entre Almacenes'), ('MARKETPLACE', 'Integración con Marketplace'), ('CADUCIDAD', 'Alerta de Caducidad')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('ALERTA', 'Alerta'), ('RESERVA', 'Reserva'), ('CANCELACION', 'Cancelación de Reserva')], max_length=50),
        ),
    ]
